version: '3.8'

services:
  healthcare-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthcare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  streamlit:
    build:
      context: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - healthcare-db
    environment:
      - DB_HOST=healthcare-db
      - DB_NAME=healthcare
      - DB_USER=postgres
      - DB_PASS=postgres

volumes:
  postgres_data: